In [1]:
##by using ufunc additional argument
##addition
import numpy as np
x=np.array([1,2234,324,321])
y=np.array([232,354,232,1332])
z=np.add(x,y)
print(z)

[ 233 2588  556 1653]


In [2]:
#substraction
import numpy as np
x=np.array([1,2234,324,321])
y=np.array([232,354,232,1332])
z=np.subtract(x,y)
print(z)

[ -231  1880    92 -1011]


In [3]:
##multiplication
import numpy as np
x=np.array([1,2234,324,321])
y=np.array([232,354,232,1332])
z=np.multiply(x,y)
print(z)

[   232 790836  75168 427572]


In [4]:
##division
import numpy as np
x=np.array([1,2234,324,321])
y=np.array([232,354,232,1332])
z=np.divide(x,y)
print(z)

[4.31034483e-03 6.31073446e+00 1.39655172e+00 2.40990991e-01]


In [5]:
#power() fundtion value from 1st array to power of value of 2nd array to return new array
import numpy as np
x=np.array([1,2,3,4])
y=np.array([3,4,5,8])
z=np.power(x,y)
print(z)

[    1    16   243 65536]


In [6]:
#reminder - mod()     reminder()    return reminder of 1 st array corrosponding to 2nd array and result in new array
import numpy as np
x=np.array([100,20,3989,4090])
y=np.array([3,4,5,8])
z=np.mod(x,y)
print(z)  
##reminder
import numpy as np
x=np.array([100,20,3989,4090])
y=np.array([3,4,5,8])
z=np.remainder(x,y)
print(z)

[1 0 4 2]
[1 0 4 2]


In [7]:
##quotient and mod(reminder)
#divmod() return both quotient and mod(reminder)
import numpy as np
x=np.array([100,20,3989,4090])
y=np.array([3,4,5,8])
z=np.remainder(x,y)
print(z)

[1 0 4 2]


In [8]:
##absolute() and abs() - do same operation but here we should use absolute() to avoid confusion with python in bulit function
##math.abs()
import numpy as np
x=np.array([-100,-20,-3989,-4090])
z=np.absolute(x)
print(z)


[ 100   20 3989 4090]
