In [1]:
##filtering miply getting some elements out and creating new array
##a boolean index list is list of boolean corresponding to index in array
import numpy as np
x=np.array([1,232,45,654,32])
y=np.array([True,False,True,False,True])
z=x[y]
print(z)                                        #[ 1 45 32]


[ 1 45 32]


In [2]:
##by filtering
##printing number higher than 5
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array=[]
for i in x:
    if i>5:
        array.append(True)
    else:
        array.append(False)
z=x[array]
print(z)
print(array)

[ 6  7  8  9 10 11 12]
[False, False, False, False, False, True, True, True, True, True, True, True]


In [3]:
##creating filter array of even elements
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array=[]
for i in x:
    if i%2==0:
        array.append(True)
    else:
        array.append(False)
z=x[array]
print(z)

[ 2  4  6  8 10 12]


In [4]:
##filter array direct by orignal array
import numpy as np
x=np.array([1,232,45,654,32,55,323,66,33,])
y=x>100                                         ##direct assinginf condition rather than true false
z=x[y]
print(y)
print(z)

[False  True False  True False False  True False False]
[232 654 323]


In [5]:
##even numnber
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y=x%2==0                 ##direct assinginf condition rather than true false
z=x[y]
print(y)
print(z)

[False  True False  True False  True False  True False  True False  True]
[ 2  4  6  8 10 12]
