In [1]:
##rounding decimal- 5 ways in numpy :truncation,fix,rounding,floor,ceil
##truncation:trunc() and fix()
##these command remove decimal and return integer closest to zero
import numpy as np
x=np.array([12.32,23.44,3.24,3.34,.34,24.99,-32.3])
z=np.trunc(x)
print(x)
print(z)
y=np.fix(x)
print(y)

[ 12.32  23.44   3.24   3.34   0.34  24.99 -32.3 ]
[ 12.  23.   3.   3.   0.  24. -32.]
[ 12.  23.   3.   3.   0.  24. -32.]


In [2]:
##rounding rounoff use around()
x=np.array([12.32,23.44,3.24,3.34,.34,24.99,-32.3])
z=np.around(x)
print(x)
print(z)

[ 12.32  23.44   3.24   3.34   0.34  24.99 -32.3 ]
[ 12.  23.   3.   3.   0.  25. -32.]


In [3]:
#floor() round off decimal to lower integer
x=np.array([12.32,23.44,3.24,3.34,.34,24.99,-32.3])
z=np.floor(x)
print(x)
print(z) 

[ 12.32  23.44   3.24   3.34   0.34  24.99 -32.3 ]
[ 12.  23.   3.   3.   0.  24. -33.]


In [4]:
##ceil() round off decimal to greater interger
x=np.array([12.32,23.44,3.24,3.34,.34,24.99,-32.3])
z=np.ceil(x)
print(x)
print(z) 

[ 12.32  23.44   3.24   3.34   0.34  24.99 -32.3 ]
[ 13.  24.   4.   4.   1.  25. -32.]
