In [1]:
## set collection of unique elements
##creating set use unique()  method to find unqiue elements from any array
##we will convert the array with repated element into set
import numpy as np
x=np.array([1,1,1,2,34,4,55,66,55,3,2,124,5,4])
y=np.unique(x)
print(y)

[  1   2   3   4   5  34  55  66 124]


In [2]:
## to fine from 2 array union
import numpy as np
x=np.array([1,1,1,2,34,4,55,66,55,3,2,124,5,4])
z=np.array([11,13,165,21,342,4,255,266,755,3,2,124,5,4])
y=np.union1d(x,z)
print(y)

[  1   2   3   4   5  11  13  21  34  55  66 124 165 255 266 342 755]


In [3]:
##intersection
import numpy as np
x=np.array([1,1,1,2,34,4,55,66,55,3,2,124,5,4])
z=np.array([11,13,165,21,342,4,255,266,755,3,2,124,5,4])
y=np.intersect1d(x,z,assume_unique=True)
print(y)

[  1   1   2   2   3   4   4   4   5  55 124]


In [4]:
##value only in 1st array not in 2nd array
import numpy as np
x=np.array([1,1,1,2,34,4,55,66,55,3,2,124,5,4])
z=np.array([11,13,165,21,342,4,255,266,755,3,2,124,5,4])
y=np.setdiff1d(x,z,assume_unique=True)
print(y)

[ 1  1  1 34 55 66 55]


In [5]:
##value that are not in both sets use setxorld()
import numpy as np
x=np.array([1,1,1,2,34,4,55,66,55,3,2,124,5,4])
z=np.array([11,13,165,21,342,4,255,266,755,3,2,124,5,4])
y=np.setxor1d(x,z,assume_unique=True)
print(y)

[ 11  13  21  34  66 165 255 266 342 755]
