In [1]:
##in numpy fnc sort() use for sorting array
import numpy as np
x=np.array([1111,222,33,34,79,7875,9867])
print(np.sort(x))

[  33   34   79  222 1111 7875 9867]


In [2]:
##sorting of alphabets
import numpy as np
x=np.array(['sun','moon','earth','divyanshi','asman','jamin'])
print(np.sort(x))

['asman' 'divyanshi' 'earth' 'jamin' 'moon' 'sun']


In [3]:
##sorting boolean value
import numpy as np
x=np.array([True,False,True,False])
print(np.sort(x))

[False False  True  True]


In [4]:
##sorting of 2D array
import numpy as np
x=np.array([[1,2,3,6756],[212,434,25,235]])
print(np.sort(x))

[[   1    2    3 6756]
 [  25  212  235  434]]
